; HOME_SENSE — ESP32 edge (DHT11 + ZMPT101B + MQTT)
; Ver secrets em include/secrets.h (copie de secrets.example.h)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
build_src_filter = +<*> -<.git/> -<.svn/>
